/**
 * Input types contains all the possible input types for the BAL layer.
 * This will generally be the result of types generated bye Nexus GraphQL generator.
 */

import { NexusGenInputs, NexusGenEnums } from '../NexusTypegen';


export type AssetStoreInput = NexusGenInputs['AssetStoreInput'];
export type ImageInput = NexusGenInputs['ImageInput'];

export type PostInput = NexusGenInputs['PostInput'];
export type PostSettingsInput = Omit<NexusGenInputs['PostSettingsInput'], 'tags'> & {
  tags?: string[];
};

export type TagInput = NexusGenInputs['TagInput'];
export type EmailConfigInput = NexusGenInputs['EmailConfigInput'];
export type AppConfigInput = NexusGenInputs['AppConfigInput'];

export type UserInput = NexusGenInputs['UserInput'];
export type NewPublicationInput = NexusGenInputs['NewPublicationInput'];
export type Credentials = NexusGenInputs['Credentials'];

export type GrantType = NexusGenEnums['GrantType'];
